upload_image:
    path: /upload-image
    methods: [POST]
    controller: App\Controller\YourController::uploadImage




app_annonce_search_ajax:
    path: /annonce/search_ajax
    controller: App\Controller\AnnonceController::searchAjax
