<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDGkLmsb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDGkLmsb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDGkLmsb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDGkLmsb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDGkLmsb\App_KernelDevDebugContainer([
    'container.build_hash' => 'DGkLmsb',
    'container.build_id' => 'cbbb5278',
    'container.build_time' => 1677819288,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDGkLmsb');
