<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLilfbtS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLilfbtS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLilfbtS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLilfbtS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLilfbtS\App_KernelDevDebugContainer([
    'container.build_hash' => 'LilfbtS',
    'container.build_id' => '9368e938',
    'container.build_time' => 1676998839,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLilfbtS');
