<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_utilisateur' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::index'], [], [['text', '/utilisateur']], [], [], []],
    'app_profile' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::profile'], [], [['text', '/profile']], [], [], []],
    'app_landing' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::landing'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::login'], [], [['text', '/login']], [], [], []],
    'app_signup' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::sigup'], [], [['text', '/signup']], [], [], []],
    'app_changepwd' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::changemdp'], [], [['text', '/changepwd']], [], [], []],
    'app_modifierpro' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::modifierpro'], [], [['text', '/modifierpro']], [], [], []],
    'app_forget' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::forget'], [], [['text', '/forget']], [], [], []],
    'app_resetpwd' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::resetpwd'], [], [['text', '/resetpwd']], [], [], []],
    'app_dashLog' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::dashLog'], [], [['text', '/dashLog']], [], [], []],
    'app_dashForget' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::dashForget'], [], [['text', '/dashForget']], [], [], []],
    'app_dashReset' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::dashReset'], [], [['text', '/dashReset']], [], [], []],
    'app_dashListe' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::dashListe'], [], [['text', '/dashListe']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
